version: '3.1'

services:
  postgres:
    image: postgres
    container_name: my-postgres-container
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
